### ISSUE TITLE
Rake missing from Gemfile

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/phase-3-object-relations-practice-code-challenge-magazines-many-many#4]
### Canvas Link

not currently on Canvas

### Concern

I still use this practice code challenge, even though it isn't published as part of the curriculum.

### Additional Context

Rake is missing from gems making it impossible to run `rake console` without adding the rake gem.

### Suggested Changes

Add `rake` gem to Gemfile.

**Comment by lantzbuilds** [comment]
This also speaks to the adjacent issue that there are not enough practice code challenges for our current Phase 3

**Comment by lizbur10** [comment]
@betalantz I've added rake to the gemfile, but I'm leaving this issue open for @professor-ben. Ben, see Lantz's second comment.
